import { describe, expect, it, vi } from 'vitest';
import { createSanction } from '@/features/sanctions/useCases/createSanction';
import type { CreateSanctionDeps } from '@/features/sanctions/ports';
import type { Sanction } from '@/features/sanctions/domain/types';

function makeSanction(overrides: Partial<Sanction> = {}): Sanction {
	return {
		id: 1,
		user_id: 42,
		type: 'strike',
		reason: 'test',
		expires_at: null,
		created_at: '2026-05-22 10:00:00',
		created_by_steamid64: '76561198000000000',
		cancelled_at: null,
		cancelled_by_steamid64: null,
		cancelled_reason: null,
		auto_generated: 0,
		original_expires_at: null,
		expires_updated_by_steamid64: null,
		...overrides
	};
}

function makeDeps(overrides: Partial<CreateSanctionDeps['repo']> = {}): CreateSanctionDeps {
	return {
		repo: {
			createSanction: vi.fn(() => ({ success: true as const, sanction: makeSanction() })),
			getActiveStrikesForUser: vi.fn(() => []),
			cancelSanction: vi.fn(() => ({ success: true as const })),
			...overrides
		}
	};
}

describe('createSanction', () => {
	it('creates a site ban with computed expiry', () => {
		const deps = makeDeps();
		const result = createSanction(deps, {
			userId: 42,
			type: 'site_ban',
			reason: 'Abuse',
			durationMinutes: 1440,
			createdBySteamId64: '76561198000000000'
		});

		expect(result.success).toBe(true);
		expect(deps.repo.createSanction).toHaveBeenCalledOnce();
		const call = vi.mocked(deps.repo.createSanction).mock.calls[0][0];
		expect(call.type).toBe('site_ban');
		expect(call.expiresAt).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
		expect(call.autoGenerated).toBe(false);
	});

	it('creates a permanent ban when durationMinutes is null', () => {
		const deps = makeDeps();
		createSanction(deps, {
			userId: 42,
			type: 'server_ban',
			reason: 'Cheating',
			durationMinutes: null,
			createdBySteamId64: '76561198000000000'
		});

		const call = vi.mocked(deps.repo.createSanction).mock.calls[0][0];
		expect(call.expiresAt).toBeNull();
	});

	it('creates a strike with 1-month expiry regardless of durationMinutes', () => {
		const deps = makeDeps();
		createSanction(deps, {
			userId: 42,
			type: 'strike',
			reason: 'Warning',
			durationMinutes: 9999,
			createdBySteamId64: '76561198000000000'
		});

		const call = vi.mocked(deps.repo.createSanction).mock.calls[0][0];
		expect(call.expiresAt).not.toBeNull();
	});

	it('does not escalate when fewer than 3 active strikes', () => {
		const deps = makeDeps({
			getActiveStrikesForUser: vi.fn(() => [makeSanction(), makeSanction()])
		});

		const result = createSanction(deps, {
			userId: 42,
			type: 'strike',
			reason: 'Warning',
			durationMinutes: null,
			createdBySteamId64: '76561198000000000'
		});

		expect(result).toEqual({ success: true, autoEscalation: false });
		expect(deps.repo.createSanction).toHaveBeenCalledTimes(1);
	});

	it('auto-escalates to server ban when 3+ active strikes', () => {
		const strikes = [
			makeSanction({ id: 10 }),
			makeSanction({ id: 11 }),
			makeSanction({ id: 12 })
		];
		const deps = makeDeps({
			getActiveStrikesForUser: vi.fn(() => strikes)
		});

		const result = createSanction(deps, {
			userId: 42,
			type: 'strike',
			reason: 'Third strike',
			durationMinutes: null,
			createdBySteamId64: '76561198000000000'
		});

		expect(result).toEqual({ success: true, autoEscalation: true });
		expect(deps.repo.createSanction).toHaveBeenCalledTimes(2);

		const autoBanCall = vi.mocked(deps.repo.createSanction).mock.calls[1][0];
		expect(autoBanCall.type).toBe('server_ban');
		expect(autoBanCall.reason).toBe('auto:3_active_strikes');
		expect(autoBanCall.autoGenerated).toBe(true);
		expect(autoBanCall.expiresAt).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);

		expect(deps.repo.cancelSanction).toHaveBeenCalledTimes(3);
		for (const strike of strikes) {
			expect(deps.repo.cancelSanction).toHaveBeenCalledWith({
				sanctionId: strike.id,
				cancelledBySteamId64: '76561198000000000',
				cancelledReason: 'auto:escalated_to_server_ban'
			});
		}
	});

	it('does not escalate for non-strike types', () => {
		const deps = makeDeps();
		createSanction(deps, {
			userId: 42,
			type: 'site_ban',
			reason: 'Ban',
			durationMinutes: 1440,
			createdBySteamId64: '76561198000000000'
		});

		expect(deps.repo.getActiveStrikesForUser).not.toHaveBeenCalled();
	});

	it('returns error when repo fails', () => {
		const deps = makeDeps({
			createSanction: vi.fn(() => ({ success: false as const, error: 'user_not_found' as const }))
		});

		const result = createSanction(deps, {
			userId: 999,
			type: 'strike',
			reason: 'test',
			durationMinutes: null,
			createdBySteamId64: '76561198000000000'
		});

		expect(result).toEqual({ success: false, error: 'user_not_found' });
	});
});
