import type { CreateSanctionDeps, CreateSanctionRepoResult } from '../ports';
import type { SanctionType } from '../domain/types';

export type CreateSanctionInput = {
	userId: number;
	type: SanctionType;
	reason: string;
	durationMinutes: number | null;
	createdBySteamId64: string;
};

export type CreateSanctionResult =
	| { success: true; autoEscalation?: boolean }
	| { success: false; error: string };

function computeExpiresAt(type: SanctionType, durationMinutes: number | null): string | null {
	if (type === 'strike') {
		const d = new Date();
		d.setMonth(d.getMonth() + 1);
		return d.toISOString().replace('T', ' ').replace('Z', '').slice(0, 19);
	}
	if (durationMinutes === null) return null;
	const d = new Date();
	d.setMinutes(d.getMinutes() + durationMinutes);
	return d.toISOString().replace('T', ' ').replace('Z', '').slice(0, 19);
}

export function createSanction(
	deps: CreateSanctionDeps,
	input: CreateSanctionInput
): CreateSanctionResult {
	const expiresAt = computeExpiresAt(input.type, input.durationMinutes);

	const result: CreateSanctionRepoResult = deps.repo.createSanction({
		userId: input.userId,
		type: input.type,
		reason: input.reason,
		expiresAt,
		createdBySteamId64: input.createdBySteamId64,
		autoGenerated: false
	});

	if (!result.success) return { success: false, error: result.error };

	let autoEscalation = false;
	if (input.type === 'strike') {
		const activeStrikes = deps.repo.getActiveStrikesForUser({ userId: input.userId });
		if (activeStrikes.length >= 3) {
			const banExpires = new Date();
			banExpires.setDate(banExpires.getDate() + 7);
			const banExpiresAt = banExpires.toISOString().replace('T', ' ').replace('Z', '').slice(0, 19);

			deps.repo.createSanction({
				userId: input.userId,
				type: 'server_ban',
				reason: 'auto:3_active_strikes',
				expiresAt: banExpiresAt,
				createdBySteamId64: input.createdBySteamId64,
				autoGenerated: true
			});

			for (const strike of activeStrikes) {
				deps.repo.cancelSanction({
					sanctionId: strike.id,
					cancelledBySteamId64: input.createdBySteamId64,
					cancelledReason: 'auto:escalated_to_server_ban'
				});
			}

			autoEscalation = true;
		}
	}

	return { success: true, autoEscalation };
}
