import type { Sanction, SanctionType, SanctionWithCallsign, PublicSanctionEntry } from './domain/types';

export type CreateSanctionRepoResult =
	| { success: true; sanction: Sanction }
	| { success: false; error: 'user_not_found' | 'database_error' };

export type CancelSanctionRepoResult =
	| { success: true }
	| { success: false; error: 'not_found' | 'already_cancelled' | 'database_error' };

export type UpdateSanctionExpiryRepoResult =
	| { success: true }
	| { success: false; error: 'not_found' | 'already_cancelled' | 'database_error' };

export type ProcessStrikeEscalationRepoResult = {
	autoBansCreated: number;
};

export type SanctionsRepo = {
	getActiveSiteBanForUser: (input: { userId: number }) => Sanction | null;
	getActiveServerBanForUser: (input: { userId: number }) => Sanction | null;
	getActiveStrikesForUser: (input: { userId: number }) => Sanction[];
	getSanctionsForUser: (input: { userId: number }) => PublicSanctionEntry[];
	listSanctions: (input: {
		page: number;
		pageSize: number;
		query?: string;
		typeFilter?: SanctionType | null;
	}) => { sanctions: SanctionWithCallsign[]; total: number };
	countSanctionsByType: (typeFilter: SanctionType | 'all') => number;
	listPublicSanctions: (input: { page: number; pageSize: number; query?: string; typeFilter?: SanctionType | null; statusFilter?: 'active' | null }) => { sanctions: PublicSanctionEntry[]; total: number };
	createSanction: (input: {
		userId: number;
		type: SanctionType;
		reason: string;
		expiresAt: string | null;
		createdBySteamId64: string;
		autoGenerated: boolean;
	}) => CreateSanctionRepoResult;
	cancelSanction: (input: {
		sanctionId: number;
		cancelledBySteamId64: string;
		cancelledReason: string;
	}) => CancelSanctionRepoResult;
	processStrikeEscalation: (input: { createdBySteamId64: string }) => ProcessStrikeEscalationRepoResult;
	updateSanctionExpiry: (input: { sanctionId: number; newExpiresAt: string | null; updatedBySteamId64: string }) => UpdateSanctionExpiryRepoResult;
};

export type CreateSanctionDeps = {
	repo: Pick<SanctionsRepo, 'createSanction' | 'getActiveStrikesForUser' | 'cancelSanction'>;
};

export type CancelSanctionDeps = {
	repo: Pick<SanctionsRepo, 'cancelSanction'>;
};

export type ListSanctionsDeps = {
	repo: Pick<SanctionsRepo, 'listSanctions' | 'countSanctionsByType'>;
};

export type ListPublicSanctionsDeps = {
	repo: Pick<SanctionsRepo, 'listPublicSanctions'>;
};

export type GetUserSanctionsDeps = {
	repo: Pick<SanctionsRepo, 'getSanctionsForUser'>;
};

export type CheckSiteBanDeps = {
	repo: Pick<SanctionsRepo, 'getActiveSiteBanForUser'>;
};

export type UpdateSanctionExpiryDeps = {
	repo: Pick<SanctionsRepo, 'updateSanctionExpiry'>;
};

export type ProcessStrikeEscalationDeps = {
	repo: Pick<SanctionsRepo, 'processStrikeEscalation'>;
};
